var currentLayout='single';var currentFace='A';var currentArtImage='';var currentArtImageB='';var currentSetSymbol='';var currentSignature='';var cardDataB={};
document.addEventListener('DOMContentLoaded',function(){setLanguage(currentLang);initNavigation();document.getElementById('lang-select').value=currentLang;document.getElementById('lang-select').addEventListener('change',function(e){setLanguage(e.target.value)})});
function initNavigation(){document.getElementById('btn-create').addEventListener('click',function(){showScreen('type-select-screen')});document.getElementById('btn-collection').addEventListener('click',function(){showScreen('collection-screen');loadCollection()});document.getElementById('btn-back-home').addEventListener('click',function(){showScreen('home-screen')});document.getElementById('btn-back-home2').addEventListener('click',function(){showScreen('home-screen')});document.getElementById('btn-back-type').addEventListener('click',function(){showScreen('type-select-screen')});document.querySelectorAll('.card-type-btn').forEach(function(btn){btn.addEventListener('click',function(){currentLayout=btn.dataset.layout;resetEditor();initEditor(currentLayout);showScreen('editor-screen')})});document.getElementById('btn-save-card').addEventListener('click',saveCard);document.getElementById('btn-export-card').addEventListener('click',exportCardPNG);document.getElementById('btn-copy-card').addEventListener('click',copyCardClipboard)}
function showScreen(id){document.querySelectorAll('.screen').forEach(function(s){s.classList.remove('active')});document.getElementById(id).classList.add('active')}
function resetEditor(){currentArtImage='';currentArtImageB='';currentSetSymbol='';currentSignature='';currentFace='A';cardDataB={};document.getElementById('field-name').value='';document.getElementById('field-supertype').value='';document.getElementById('field-type').value='';document.getElementById('field-subtype').value='';document.getElementById('field-rules').value='';document.getElementById('field-flavor').value='';document.getElementById('field-power').value='';document.getElementById('field-toughness').value='';document.getElementById('field-artist').value='';document.getElementById('field-border').value='black';document.getElementById('mana-chosen').innerHTML='';document.getElementById('preview-art').innerHTML='<div class=art-placeholder>Clicca per immagine</div>';document.getElementById('set-preview').innerHTML=''}
function getCollection(){try{var d=localStorage.getItem('mise-collection');return d?JSON.parse(d):[]}catch(e){return[]}}
function saveCollection(c){localStorage.setItem('mise-collection',JSON.stringify(c))}
function saveCard(){var card=gatherCardData();if(!card.name&&!card.artImage){alert('Inserisci almeno un nome o immagine');return}var col=getCollection();card.id=Date.now().toString();card.createdAt=new Date().toISOString();col.push(card);saveCollection(col);showScreen('collection-screen');loadCollection()}
function gatherCardData(){return{layout:currentLayout,border:document.getElementById('field-border').value,name:document.getElementById('field-name').value,manaCost:getChosenMana(),supertype:document.getElementById('field-supertype').value,type:document.getElementById('field-type').value,subtype:document.getElementById('field-subtype').value,rules:document.getElementById('field-rules').value,flavor:document.getElementById('field-flavor').value,power:document.getElementById('field-power').value,toughness:document.getElementById('field-toughness').value,loyalty:document.getElementById('field-loyalty')?document.getElementById('field-loyalty').value:'',rarity:document.getElementById('field-rarity').value,artist:document.getElementById('field-artist').value,artImage:currentArtImage,setSymbol:currentSetSymbol,faceB:cardDataB}}
function getChosenMana(){var imgs=document.getElementById('mana-chosen').querySelectorAll('img');return Array.from(imgs).map(function(i){return i.dataset.symbol})}
function exportCardPNG(){showToast('Usa screenshot per esportare (in sviluppo)')}
function copyCardClipboard(){showToast('Usa screenshot per copiare (in sviluppo)')}
function showToast(msg){var t=document.createElement('div');t.textContent=msg;t.style.cssText='position:fixed;bottom:20px;left:50%;transform:translateX(-50%);background:#333;color:#fff;padding:10px 20px;border-radius:6px;z-index:9999;font-size:14px';document.body.appendChild(t);setTimeout(function(){t.remove()},2000)}